[tool.poetry]
name = "sign_language_translator"
version = "0.3.0"
description = "Translate between spoken/text and sign language using AI."
authors = ["Mudassar Iqbal <mdsriqb@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "sign_language_translator"}]
repository = "https://github.com/sign-language-translator/sign-language-translator"
keywords = ["sign", "translation", "pose", "pakistan", "deep-learning", "computer-vision", "nlp", "sign-language", "sign-language-translation"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-vv "
filterwarnings = [
    "ignore::DeprecationWarning",
]

[tool.isort]
profile = "black"