datasets:
  - name: sign-language-dataset-1
    version: 1.0.0
    files:
      - name: sign_recordings/collection_to_label_to_language_to_words.json
        url: https://raw.githubusercontent.com/sign-language-translator/sign-language-datasets/ebbf543e4840aa61e674941d3e84fc630d7ca47c/sign_recordings/collection_to_label_to_language_to_words.json
      - name: sign_recordings/organization_to_language_to_constructable_words.json
        url: https://raw.githubusercontent.com/sign-language-translator/sign-language-datasets/ebbf543e4840aa61e674941d3e84fc630d7ca47c/sign_recordings/organization_to_language_to_constructable_words.json
      - name: sign_recordings/recordings_labels.json
        url: https://raw.githubusercontent.com/sign-language-translator/sign-language-datasets/ebbf543e4840aa61e674941d3e84fc630d7ca47c/sign_recordings/recordings_labels.json
      - name: text_preprocessing.json
        url: https://raw.githubusercontent.com/sign-language-translator/sign-language-datasets/ebbf543e4840aa61e674941d3e84fc630d7ca47c/text_preprocessing.json
      - name: language_to_token_to_id.json
        url: https://raw.githubusercontent.com/sign-language-translator/sign-language-datasets/ebbf543e4840aa61e674941d3e84fc630d7ca47c/language_to_token_to_id.json

package_versions:
  - version: 0.4.2
    dataset_version: 1.0.0

  - version: 0.5.0
    dataset_version: 1.0.0
